// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "faa25d28-9108-4efa-8240-1ab1e976440e");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1564072996);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1563986927);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1564070866);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1564067795);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1564067675);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1564072876);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1563987167);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1563987047);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563986061);
user_pref("browser.laterrun.bookkeeping.sessionCount", 17);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{99df3877-2c4e-4770-aafa-b77e93da41c1}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1564030800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1564072651666");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1564074445666");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1564070840875");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1564074440875");
user_pref("browser.search.region", "MX");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190401101615");
user_pref("browser.slowStartup.averageTime", 1689);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190401101615");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1563986076740");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "2979322b23914bed865f4869cff9652e");
user_pref("extensions.blocklist.lastModified", "Mon, 22 Jul 2019 15:40:26 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1564072996);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190401101615");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e78da0da-a882-4818-aeff-4db3a4b444e9\",\"screenshots@mozilla.org\":\"6d381554-5c53-4237-85fe-d61adf6aee9a\",\"webcompat-reporter@mozilla.org\":\"6dcf9f52-98b1-4660-a605-add0243b5f6a\",\"webcompat@mozilla.org\":\"cd7b0972-44ae-48a9-8af4-c0352f0cc062\",\"etp-search-volume-study@shield.mozilla.org\":\"515db7cc-ccd3-42ed-99ff-b605b766e63b\",\"baidu-code-update@mozillaonline.com\":\"0a1c78ec-c0fa-44e9-ad6d-625c7b1b8b7f\",\"fxmonitor@mozilla.org\":\"22cc06dc-ad86-4be5-bea8-9a17262a232d\"}");
user_pref("idle.lastDailyNotification", 1563986560);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1564072997);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190401101615");
user_pref("media.gmp-manager.lastCheck", 1563986155);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1563986560);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "cbebb297-0b50-4d0c-88a7-744ba3257490");
user_pref("security.sandbox.plugin.tempDirSuffix", "1599a197-ef2f-455e-8440-da6309f0248d");
user_pref("services.blocklist.addons.checked", 1564072875);
user_pref("services.blocklist.gfx.checked", 1564072875);
user_pref("services.blocklist.onecrl.checked", 1564072875);
user_pref("services.blocklist.pinning.checked", 1564072875);
user_pref("services.blocklist.plugins.checked", 1564072875);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1564066175926\"");
user_pref("services.settings.last_update_seconds", 1564072875);
user_pref("services.settings.main.language-dictionaries.last_check", 1564072875);
user_pref("services.settings.main.onboarding.last_check", 1564072875);
user_pref("services.settings.main.sites-classification.last_check", 1564072875);
user_pref("services.settings.main.tippytop.last_check", 1564072875);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1563986560);
user_pref("toolkit.startup.last_success", 1564067644);
user_pref("toolkit.telemetry.cachedClientID", "2afd8456-7697-45aa-8c8f-43083e3d6c08");
user_pref("toolkit.telemetry.previousBuildID", "20190401101615");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
